### ISSUE TITLE
M4.1 | Shows completion setting twice

### ISSUE THREAD

**Issue by gemguardian** [moodleou/moodle-filter_embedquestion#24] opened 2023-03-10 08:55 UTC
Moodle version: M4.1.x
Theme: Boost 
Format: Topic 

We don't experience any real issues with the filter in M4.1 though we noticed that the activity completion criteria is shown twice on the page

We solved it for now by adding to the css:

.embedded-main .completion-info {
display:none!important;
}

![image](https://user-images.githubusercontent.com/16559999/224270242-f3de01e4-2d5e-4643-84c0-d277fd0c30a9.png)

**Comment by timhunt** [comment] 2023-03-10 10:13
That is strange. I am currently failing to understand how the display of completion infomration in the page activity could be affected by this filter.

**Comment by t-schroeder** [comment] 2023-09-18 12:29
This is the call stack that explains how the completion information of the surrounding activity gets displayed in the iframe of each embedded question:

![image](https://github.com/moodleou/moodle-filter_embedquestion/assets/24255259/74bcad69-a403-4163-8703-5bf8e63a09f7)

**Comment by timhunt** [comment] 2023-09-18 12:35
But, the page in the iframe declares

$PAGE->set_pagelayout('embedded');

So, I think this should not happen. Perhaps this needs a bug filed on the moodel core theme system?

**Comment by t-schroeder** [comment] 2023-09-18 12:37
I think this is a regression caused by [MDL-74602](https://tracker.moodle.org/browse/MDL-74602).

**Comment by t-schroeder** [comment] 2023-09-18 12:44
If I remove 

```php
$PAGE->set_pagelayout('embedded');
```

It defaults back to the `'drawers'` layout and you have an additional navbar, drawers etc. in the embedded question's iframe. That's definitely not what you want.

**Comment by timhunt** [comment] 2023-09-18 13:00
The fact MDL-74602 exists suggests that they thoguht that was a good change. However, from teh piont-of-view of this plugin, it seems lik a bad change. Perhaps ask there?

Anwyay, for now, $PAGE->activityheader->disable(); seems like a safe work-around. I will add it.

**Comment by t-schroeder** [comment] 2023-09-18 13:10
I think the changes in MDL-74602 make sense if you embed an activity somewhere. So disabling the activity header should be fine since this plugin doesn't embed activities.

**Comment by timhunt** [comment] 2023-11-10 14:27
The fix is in main, so closing this.

**Closed by timhunt** 2023-11-10 14:27 UTC
