### ISSUE TITLE
Shows "reset user tour on this page" link twice

### ISSUE THREAD

**Issue by tibbakoi** [moodleou/moodle-filter_embedquestion#27] opened 2023-08-11 08:37 UTC
Moodle version: M4.1
Theme: Catawesome
Format: Collapsed Topics

The "reset user tour on this page" link appears twice, once in the footer where intended and once below the embedded question:

<img width="536" alt="image" src="https://github.com/moodleou/moodle-filter_embedquestion/assets/25509459/8c43404f-9155-47a6-9665-c0b647c05ffa">

It also doesn't re-trigger the relevant user tour.

**Comment by timhunt** [comment] 2023-08-11 08:49
Thanks for reporting this.

I think this is a problem with the User tours system, not this plugin, so I created https://tracker.moodle.org/browse/MDL-78989.

**Comment by timhunt** [comment] 2023-11-10 14:27
I think this is a duplicate of \24, so closing.

**Closed by timhunt** 2023-11-10 14:27 UTC
